
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_GPIO_OLED_DC_DEVICE_ID,
		XPAR_AXI_GPIO_OLED_DC_BASEADDR,
		XPAR_AXI_GPIO_OLED_DC_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OLED_DC_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_OLED_RES_DEVICE_ID,
		XPAR_AXI_GPIO_OLED_RES_BASEADDR,
		XPAR_AXI_GPIO_OLED_RES_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OLED_RES_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_OLED_VBAT_DEVICE_ID,
		XPAR_AXI_GPIO_OLED_VBAT_BASEADDR,
		XPAR_AXI_GPIO_OLED_VBAT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OLED_VBAT_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_OLED_VDD_DEVICE_ID,
		XPAR_AXI_GPIO_OLED_VDD_BASEADDR,
		XPAR_AXI_GPIO_OLED_VDD_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_OLED_VDD_IS_DUAL
	}
};


